version: '3'
services:
  db:
    image: mysql
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: mydb_user
      MYSQL_PASSWORD: mydb_password
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root  
  apache:
    build: ./www/php
    container_name: apache
    ports:
      - "80:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs
    depends_on:
      - php         
  php:
    image: php:7.4-fpm
    container_name: php
    ports:
      - "9000:9000"
    volumes:
      - ./website:/usr/local/apache2/htdocs
volumes:
  db_data: {}